export const API_URL = {
  GET_QR_CODE: "/auth/generate-qr",
  GET_PLAN_DETAILS: "/plan/getPlanDetails",
  GET_PLAN_DETAILS_NEW: "/price/getLocationPrice",
  USER_ME: "/user/@me",
  SEGMENT_API_VIDEO:"/practicewithmasterCustomer/getPractice",
  GET_ATTENDANCE: "/user/attendance",
  RECORD_SESSION: "/user/record-sesion",
  GET_LOCATION: "/payment/location",
  CHECK_OUT: "/payment/create",
  add_comments: "/comments/addComment",
  GET_SEGMENTS:"/segments_new/listSegments",
  VIEW_NOTIFICATIONS: "/comments/view-notification",
  PRATICEWITH_MASTER_LIST: "/practicewithmasterCustomer/listPractices",
  PRATICEWITH_MASTER_GET_ID: "/practicewithmasterCustomer/getPractice/",
};
